# Generated by Django 4.0.4 on 2022-05-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_article_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='img1',
            field=models.ImageField(upload_to='./Templates/ArticleImages'),
        ),
    ]
