# Generated by Django 4.0.4 on 2022-06-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_media_img1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='./Templates/Segment/input')),
                ('img_id', models.CharField(max_length=100)),
            ],
        ),
    ]
